name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  publish-code-coverage:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 11
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport -Dorg.gradle.caching=false

      - name: Publish Coverage
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
        shell: bash